"""Add enabled and sorting to Community

Revision ID: 5475f3355267
Revises: 67bd1512154c
Create Date: 2023-06-17 23:29:31.705746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5475f3355267'
down_revision = '67bd1512154c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('communities', sa.Column('sorting', sa.String(length=10), server_default='hot', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'sorting')
    op.drop_column('communities', 'enabled')
    # ### end Alembic commands ###
